plugins {
    id("fpgradle-minecraft")
}

group = "com.example"

minecraft_fp {
    // optional
    // If you want to use modern java
    java {
        compatibility = modern //Convention: legacy
//        version       = JavaVersion.VERSION_XYZ //Convention, determined by compatibility
    }

    // REQUIRED
    // Basic information about the mod
    mod {
        modid   = "examplemod"   //REQUIRED
        name    = "Example Mod"  //REQUIRED
//        version = "autogenerated from git" //Convention
        rootPkg = "$group.mymod" //REQUIRED
    }

    // optional
    // For generating an -api jar
//    api {
//        packages          = listOf() //Convention
//        packagesNoRecurse = listOf() //Convention
//    }

    // optional
//    mixin {
//        pkg          = "mixins"      //optional
//        pluginClass  = "MixinPlugin" //optional, requires pkg set
//        debug        = false         //Convention
//        hasMixinDeps = false         //Convention
//    }

    // optional
//    core {
//        coreModClass                   = "Core"      //optional
//        accessTransformerFile          = "le_at.cfg" //optional
//        containsMixinsAndOrCoreModOnly = false       //Convention
//    }

    // OPTIONAL
    // Extra settings for shadowed dependencies
//    shadow {
//        minimize = false //Convention
//        relocate = false //Convention
//    }

    // optional
    // Generates string constants you can use in code
    tokens {
        tokenClass = "Tags"
//        modid      = "MOD_ID"      //Convention
//        name       = "MOD_NAME"    //Convention
//        version    = "MOD_VERSION" //Convention
//        rootPkg    = "ROOT_PKG"    //Convention
    }

    // optional
    // Use this if you want to publish on maven
//    publish {
//        repoUrl  = "https://example.com/"
//        repoName = "example"
//        sources  = true                    //Convention
//        group    = "${project.group}"      //Convention
//        artifact = "${mod.modid}-mc1.7.10" //Convention
//        version  = "${mod.version}"        //Convention
//        userEnv  = "MAVEN_DEPLOY_USER"     //Convention
//        passEnv  = "MAVEN_DEPLOY_PASSWORD" //Convention
//    }
}
